_commit: v2.2.0
_src_path: gh:mopidy/mopidy-ext-template
author_email: stein.magnus@jodal.no
author_full_name: Stein Magnus Jodal
dist_name: mopidy-mpris
ext_name: mpris
github_username: mopidy
short_description: Mopidy extension for controlling Mopidy through the MPRIS D-Bus
    interface
