_commit: v1.1.0
_src_path: gh:mopidy/mopidy-ext-template
author_email: stein.magnus@jodal.no
author_full_name: Stein Magnus Jodal
repo_name: mopidy-mpris
dist_name: Mopidy-MPRIS
ext_name: mpris
github_username: mopidy
short_description: Mopidy extension for controlling Mopidy through the MPRIS D-Bus interface
